### ISSUE TITLE
/genie test <wish> returns that argument <wish> is required

### ISSUE THREAD

**Issue by s1h4d0w** [Rsl1122/Genie#13]
The test feature doesn't seem to work, it does not recognize the wish. I've tried it in several ways:

- /genie test elytra
- /genie test I want an elytra
- /genie test "I want an elytra"

![image](https://user-images.githubusercontent.com/5654654/37565566-c9c5a06a-2aab-11e8-89d4-2a6820d1a933.png)

**Comment by AuroraLS3** [comment]
Will investigate

**Comment by AuroraLS3** [comment]
Fixed in 1.2.3
