### ISSUE TITLE
 Suggestion for improve commands for genie

### ISSUE THREAD

**Issue by CaptainLaStar** [Rsl1122/Genie#20]
I am contacting you because I am using your "Genie" plugin in 1.9.4.

First, I apologize for the translation of this text, which is not perfect to understand.

He's excellent, he's my favorite, I've been looking for him for months, however, I have a small request to ask if you will allow me.

**My request is for commands**, I would like the player to be able to receive an item by a command, for example, to hide an command that the genie will execute, (it is a option).

For example, I say "Parchment" in the chat and the genie will perform the command that points to the word "parchment". Until now, this was not available in config.yml.

**----**
Config (with an itemjoin plugin command for example) :

_(*)_Parchment: "/itemjoin give {playername} item-parchment" _(**)_

(*) = Word for the chat.
(**) = Genie executes the command.

**OR**

Player enter /parchment in the chat and (genie) execute a hidden command of the genie plugin in the config:
Config (for second example):
/Parchment: "/itemjoin give {playername} item-parchment"

**----**

Instead the player will have to do all of the ordering, he will just have to say the word "parchment" or "/parchment"for his wishes.

This will make it possible to have a new functionality which will be able to fulfill the wishes of the players by words for the commands.

Hope to have a response from you and that will be available in the next update to your plugin.
Thank you in advance :)

**Comment by AuroraLS3** [comment]
This feature is already available since 1.2.3.

In your Genie config.yml put
```
Customization:
  CommandWishes:
    - "/itemjoin give {playername} item-parchment | parchment"
```
