### ISSUE TITLE
An internal error occured...

### ISSUE THREAD

**Issue by Xosmuits** [Rsl1122/Genie#5]
https://hastebin.com/adirapizaq.vbs

I'm using 1.8.8 spigot and here's the errors.

**Comment by AuroraLS3** [comment]
Alright imma fix that. (test command requires arguments)

**Comment by Xosmuits** [comment]
It does not matter, even if I use arguments same errors occur.

**Comment by AuroraLS3** [comment]
Alright thanks for the info.
